name: Lint

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Golangci
        uses: golangci/golangci-lint-action@v6.1.0
