name: Release

on:
  push:
    branches:
      - github-actions/main

permissions:
  contents: write
  pull-requests: write
  # workflows: write # Can't set here but needed on the PAT

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_GITHUB_TOKEN }}
          target-branch: ${{ github.ref_name }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
